services:
  utapractice:
    build: .
    container_name: utapractice
    ports:
      - "8502:8501"
    volumes:
      - ./data/songs:/app/songs
      - ./data/songs_archived:/app/songs_archived
      - ./data/song_db.json:/app/song_db.json
      - ./data/lyrics_jobs.json:/app/lyrics_jobs.json
      - ./data/settings.local.json:/app/settings.local.json
    restart: always
    labels:
      watchcow.enable: "true"
      watchcow.display_name: "练歌"
      watchcow.service_port: "8502"
      watchcow.protocol: "http"
      watchcow.path: "/"
